# Generated by Django 5.0.3 on 2024-04-14 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('destination', models.CharField(default='Default', max_length=50)),
                ('source', models.CharField(default='Default', max_length=50)),
                ('seatType', models.CharField(default='Default', max_length=50)),
                ('slot', models.CharField(default='Default', max_length=50)),
                ('Date1', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
